version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - arities
  - cargs
  - combinators
  - Disjointness
  - fargs
  - gname
  - msgen
  - paiges
  - repsep
  - scalac
  - scalactic
  - scalatest
  - spsc
  - supercompiler
  - Symb
ignoreWords: []
import: []
